version: '3'

services:
    web:
        image: nginx:1.19-alpine
        restart: always
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        labels:
            traefik.enable: true
            traefik.frontend.rule: 'Host: ${HOST_NAME}'
        networks:
            - mailhog_internal
            - traefik

    smtp:
        image: 'mailhog/mailhog:v1.0.0'
        restart: always
        networks:
            mailhog:
                aliases:
                    - mailhog
            mailhog_internal:
                aliases:
                    - smtp

networks:
    mailhog:
        external: true
    mailhog_internal:
        internal: true
    traefik:
        external: true
